In [1]:
import pandas as pd

## Creating Data 
there are 2 core objects in pandas: the **DataFrame** and the **Series**  
i) **DataFrame** - is a table

In [2]:
#consider:
pd.DataFrame({'Yes': [50, 21], 'No': [131, 2]})

   Yes   No
0   50  131
1   21    2

In [3]:
#DataFrame can also be string values:
pd.DataFrame({'Bob':['I liked it.', 'It was awful.'], 'Sue': ['Pretty good.', 'Bland.']})

             Bob           Sue
0    I liked it.  Pretty good.
1  It was awful.        Bland.

we are using pd.DataFrame() constructor to generate these DataFrame objects. 
the syntax for declaring a new one is a dictionary whose keys are the column names and whose values are a list of entries

the dictionary list constructor assigns values to the column labels, but just uses an ascending count from 0(0,1,2,....n) for the row labels. Sometimes this is okay but we may also want to set these labels ourselves 

the list of row labels used in a DataFrame is known as an **Index**. we can assign values to it using an _index_ parameter in our constructor:

In [4]:
pd.DataFrame({'Bob': ['I liked it', 'It was awful.'], 
              'Sue': ['Pretty Good.', 'Bland.']}, 
             index=["Product A", 'Product B'])

                     Bob           Sue
Product A     I liked it  Pretty Good.
Product B  It was awful.        Bland.

ii) **Series** is a sequence of data values.  
    If a DataFrame is a table, a Series is a list.

In [5]:
#In fact you can even create one with nothing more than a list 
pd.Series([1,2,3,4,5])

0    1
1    2
2    3
3    4
4    5
dtype: int64

A **Series** is a single column of a DataFrame. So you can assign row labels in the Series the same way as before, using an _index_ parameter. 
A Series does not have a column name, only one overall name:

In [6]:
pd.Series([30,35,40], 
          index=['2015 Sales', '2016 Sales', '2017 Sales'], 
          name='Product A')

2015 Sales    30
2016 Sales    35
2017 Sales    40
Name: Product A, dtype: int64

the Series and the DataFrame are closely related. Think of a Dataframe as a bunch of Series "glued together"